# Generated by Django 5.2 on 2025-04-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('college', 'College'), ('study', 'Study'), ('fitness', 'Fitness')], default='college', max_length=20),
        ),
    ]
